name       : sound-juicer
version    : 3.40.0
release    : 13
source     :
    - https://download.gnome.org/sources/sound-juicer/3.40/sound-juicer-3.40.0.tar.xz : 2ee882744391beb4c6d64a0f6825fb765510b706ec2b704bfb42e42afaae1de6
license    : GPL-2.0-only
component  : multimedia.audio
summary    : Sound Juicer is a GNOME CD ripper.
description: |
    A lean and friendly audio CD extractor for GNOME.
builddeps  :
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(iso-codes)
    - pkgconfig(libbrasero-media3)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libdiscid)
    - pkgconfig(libmusicbrainz5)
    - gstreamer-1.0-plugins-good
    - itstool
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/doc
