name       : sound-juicer
version    : 3.38.0
release    : 10
source     :
    - https://download.gnome.org/sources/sound-juicer/3.38/sound-juicer-3.38.0.tar.xz : ae375f357a1b8b81e4aff737c9d6c98bc2dadfe20e71754b1d52a79f036aa521
license    : GPL-2.0-only
component  : multimedia.audio
summary    : Sound Juicer is a GNOME CD ripper.
description: |
    A lean and friendly audio CD extractor for GNOME.
builddeps  :
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(iso-codes)
    - pkgconfig(libbrasero-media3)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libdiscid)
    - pkgconfig(libmusicbrainz5)
    - gstreamer-1.0-plugins-good
    - itstool
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/doc