name       : sound-juicer
version    : 3.20.0
release    : 1
source     :
    - https://download.gnome.org/sources/sound-juicer/3.20/sound-juicer-3.20.0.tar.xz : 77e2b75f3f6fa82fc182ad782afe93c1be8d227979c80a7db9c5c54520d50c1a
license    : GPL-2.0
component  : multimedia.audio 
summary    : Sound Juicer is a GNOME CD ripper.
description: |
    A lean and friendly audio CD extractor for GNOME. 
builddeps  :
    - itstool
    - pkgconfig(gio-2.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(iso-codes)
    - pkgconfig(libbrasero-media3)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libdiscid)
    - pkgconfig(libmusicbrainz5)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
