name       : sound-juicer
version    : 3.24.0
release    : 7
source     :
    - https://download.gnome.org/sources/sound-juicer/3.24/sound-juicer-3.24.0.tar.xz : de6ae3889e60a572221274517a90d29dd21023acf3a94cc9c033270776270fa7
license    : GPL-2.0-only
component  : multimedia.audio
summary    : Sound Juicer is a GNOME CD ripper.
description: |
    A lean and friendly audio CD extractor for GNOME.
builddeps  :
    - pkgconfig(gio-2.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(iso-codes)
    - pkgconfig(libbrasero-media3)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libdiscid)
    - pkgconfig(libmusicbrainz5)
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
